### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by betovelandia** [DangerCove/Spotify-AppleScript-Patch#1]
Just wanted to say thanks, This was really annoying, they should open source Bowtie :\

**Comment by betovelandia** [comment]
Hmm actually I talked too fast, I still can't see the art of some Spotify albums, I'll check if it doesn't happens on iTunes as well. Any ideas ?

**Comment by boyvanamstel** [comment]
Getting album art from Spotify using AppleScript is broken in a way that my simple patch can't fix.

Luckily Spotify has mentioned that an update that addresses these issues is about to be released.
