### ISSUE TITLE
Can't get this to work

### ISSUE THREAD

**Issue by itsbrex** [DangerCove/Spotify-AppleScript-Patch#2]
Running Spotify v1.0.24.104.g92a22684 (1.0.24.104.g92a22684-32) on Mac OS X 10.11.3 (15D21)

When I open the app it says it's already done. Doesn't allow me to click anything & no file is created on the desktop. 

Could it have something to do with my /Application folder's permissions?

![mmnu2jaoiy](https://cloud.githubusercontent.com/assets/9772694/13686732/21c842ac-e6cc-11e5-97b6-c57b14f73a79.gif)

![2016-03-10 at 2 28 pm](https://cloud.githubusercontent.com/assets/9772694/13686778/641beec4-e6cc-11e5-982b-ac36aea86614.jpg)

**Comment by boyvanamstel** [comment]
Hi there, this was a temporary fix for when Spotify accidentally disabled AppleScript support in their desktop app. The issue has since been resolved and there's really no reason to use it anymore.

I'm just keeping it online for educational purposes.
